# Variables defined for DEV environment
replicaCount: 2
image:
  repository: yuvrajone/mytomorrow
  tag: v1.0.1
  pullPolicy: IfNotPresent
env:
  LOG_LEVEL: DEBUG
  MAX_CONNECTIONS: "5"
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  minAvailable: 2
  targetCPUUtilizationPercentage: 80
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "200m"
    memory: "200Mi"

