replicaCount: 3
image:
  repository: yuvrajone/mytomorrow
  tag: v1.0.3
  pullPolicy: IfNotPresent
env:
  LOG_LEVEL: info
  MAX_CONNECTIONS: "9"
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70


