# Variables defined for PROD env
replicaCount: 1
image:
  repository: yuvrajone/project
  tag: v1.0.24
  pullPolicy: IfNotPresent
env:
  LOG_LEVEL: info
  MAX_CONNECTIONS: "9"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70
pdbMinAvailable: 1
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "200m"
    memory: "200Mi"


