# Define PDB to ensure that a minimum number of pods remain available during node maintenance.
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.pdbMinAvailable }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
