apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  secret_key: {{ .Values.secrets.secret_key | b64enc }}
  db_password: {{ .Values.secrets.db_password | b64enc }}
