#  listen on port 80 externally and forwards traffic to the container's port 5000.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
