# auth_enabled: false

# server:
#   http_listen_port: 3100
#   grpc_listen_port: 9095

# ingester:
#   lifecycler:
#     ring:
#       kvstore:
#         store: inmemory
#       replication_factor: 1
#   chunk_idle_period: 3m
#   max_chunk_age: 1h
#   chunk_target_size: 1048576
#   chunk_retain_period: 30s
#   wal:
#     enabled: true
#     dir: /loki/wal

# limits_config:
#   volume_enabled: true

# schema_config:
#   configs:
#     - from: 2020-10-15
#       store: boltdb-shipper
#       object_store: filesystem
#       schema: v11
#       index:
#         prefix: index_
#         period: 24h

# storage_config:
#   boltdb_shipper:
#     active_index_directory: /loki/index
#     cache_location: /loki/boltdb-cache
#     shared_store: filesystem

#   filesystem:
#     directory: /loki/chunks

# compactor:
#   working_directory: /loki/compactor
#   shared_store: filesystem

# ruler:
#   storage:
#     type: local
#     local:
#       directory: /loki/rules
#   rule_path: /loki/rules-temp
#   alertmanager_url: http://localhost:9093
#   ring:
#     kvstore:
#       store: inmemory
#   enable_api: true
